### PR TITLE
Added butts

### PR DESCRIPTION
**Pull request by sergeysova**
Added butts from http://obutts.ru

### CODE REVIEW

**Comment by yetithefoot** [comment]
@LestaD please update readme.md with description

**Comment by LestaD** [comment]
@yetithefoot already updated. https://github.com/LestaD/slack-plain-bots/blob/master/README.md

**Comment by yetithefoot** [comment]
@LestaD Deployed to Heroku, but API returns empty body sometimes.

**Comment by sergeysova** [comment]
It's trouble on obutts.ru server

**Pull request merged**
